<template>
  <AppLayout>
    <div class="space-y-6">
      <header><p class="text-sm font-medium text-primary-600 dark:text-primary-400">{{ t('admin.userRiskControl.sectionLabel') }}</p><h1 class="mt-1 text-2xl font-semibold text-gray-900 dark:text-white">{{ t('admin.userRiskControl.auditPageTitle') }}</h1><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ t('admin.userRiskControl.auditPageDescription') }}</p></header>
      <div v-if="error" class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ error }}</div>
      <section class="card p-4"><div class="grid gap-3 md:grid-cols-3"><select v-model="draft.action" class="form-input" data-testid="audit-action-filter"><option value="">{{ t('admin.userRiskControl.allActions') }}</option><option value="ban">{{ t('admin.userRiskControl.ban') }}</option><option value="unban">{{ t('admin.userRiskControl.unban') }}</option><option value="auto_ban">{{ t('admin.userRiskControl.autoBan') }}</option><option value="rule_update">{{ t('admin.userRiskControl.ruleUpdate') }}</option></select><input v-model.number="draft.targetUserId" type="number" class="form-input" :placeholder="t('admin.userRiskControl.targetUserPlaceholder')" /><select v-model="draft.result" class="form-input" data-testid="audit-result-filter"><option value="">{{ t('admin.userRiskControl.allResults') }}</option><option value="success">success</option><option value="failed">failed</option></select></div><button type="button" class="btn btn-primary mt-4" data-testid="apply-audit-filters" @click="loadAudit(true)">{{ t('common.apply') }}</button></section>
      <section class="card overflow-hidden"><div v-if="loading" class="p-12 text-center text-sm text-gray-500">{{ t('common.loading') }}</div><div v-else-if="!records.length" class="p-12 text-center text-sm text-gray-500">{{ t('admin.userRiskControl.empty') }}</div><div v-else class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-dark-700"><thead class="bg-gray-50 dark:bg-dark-800"><tr><th v-for="label in headers" :key="label" class="px-5 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">{{ label }}</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-dark-700"><tr v-for="record in records" :key="record.id"><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ formatDate(record.created_at) }}</td><td class="px-5 py-4 text-sm font-medium text-gray-900 dark:text-white">{{ record.action }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ targetLabel(record) }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ record.before_status || '-' }} → {{ record.after_status || '-' }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ record.actor || '-' }}</td><td class="px-5 py-4"><span :class="record.result === 'success' ? 'text-emerald-600' : 'text-red-600'">{{ record.result }}</span></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ record.reason || '-' }}</td></tr></tbody></table></div><footer v-if="total" class="flex items-center justify-between border-t border-gray-200 px-5 py-3 text-sm text-gray-500 dark:border-dark-700"><span>{{ t('admin.userRiskControl.total', { total }) }}</span><div class="flex items-center gap-2"><button type="button" class="btn btn-secondary btn-sm" data-testid="audit-previous-page" :disabled="page <= 1 || loading" @click="changePage(page - 1)">{{ t('common.previous') }}</button><span>{{ page }} / {{ totalPages }}</span><button type="button" class="btn btn-secondary btn-sm" data-testid="audit-next-page" :disabled="page >= totalPages || loading" @click="changePage(page + 1)">{{ t('common.next') }}</button></div></footer></section>
    </div>
  </AppLayout>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import AppLayout from '@/components/layout/AppLayout.vue'
import { userRiskControlV2API, type RiskAuditRecord } from '@/api/admin/userRiskControlV2'
const { t } = useI18n(); const records = ref<RiskAuditRecord[]>([]); const total = ref(0); const page = ref(1); const pageSize = 20; const loading = ref(true); const error = ref(''); const draft = reactive<{ action?: string; targetUserId?: number; result?: string }>({ action: '', targetUserId: undefined, result: '' }); const headers = computed(() => [t('admin.userRiskControl.table.time'), t('admin.userRiskControl.table.action'), t('admin.userRiskControl.table.target'), t('admin.userRiskControl.table.statusChange'), t('admin.userRiskControl.table.actor'), t('admin.userRiskControl.table.result'), t('admin.userRiskControl.table.reason')]); const totalPages = computed(() => Math.max(1, Math.ceil(total.value / pageSize)))
function errorMessage(err: unknown) { return typeof err === 'object' && err !== null && 'message' in err && typeof err.message === 'string' && err.message.trim() ? err.message : err instanceof Error ? err.message : t('admin.userRiskControl.loadFailed') }
async function loadAudit(resetPage = false) { if (resetPage) page.value = 1; loading.value = true; error.value = ''; try { const response = await userRiskControlV2API.listAudit({ ...draft, page: page.value, pageSize }); records.value = response.items; total.value = response.total; page.value = response.page || page.value } catch (err) { error.value = errorMessage(err) } finally { loading.value = false } }
async function changePage(next: number) { page.value = next; await loadAudit() }
function formatDate(value: string) { return value ? new Date(value).toLocaleString() : '-' }
function targetLabel(record: RiskAuditRecord) { return record.target_type === 'user' ? `#${record.target_id || record.target_user_id}` : `${record.target_type || 'unknown'}:${record.target_id || '-'}` }
onMounted(loadAudit)
</script>
