export default {
  userRiskControl: {
    sectionLabel: 'Security & Risk',
    tabsLabel: 'User risk control',
    usersTab: 'User risk',
    rulesTab: 'Scenario rules',
    auditTab: 'Operation audit',
    usersTitle: 'User Risk Control', usersDescription: 'Review real accounts and execute traceable ban or unban actions.', rulesTitle: 'Scenario Rules', rulesDescription: 'Configure risk windows, thresholds, scores, and human actions.', auditPageTitle: 'Operation Audit', auditPageDescription: 'Review ban, unban, automatic ban, and rule-change results.', searchPlaceholder: 'Search username or email', allStatuses: 'All statuses', active: 'Active', disabled: 'Disabled', allRiskTypes: 'All risk types', allRiskLevels: 'All risk levels', pendingOnly: 'Pending only', pending: 'Pending', empty: 'No matching accounts', total: '{total} records', enabled: 'Enabled', window: 'Window (seconds)', threshold: 'Threshold', score: 'Score', level: 'Risk level', action: 'Action', testRule: 'Test rule', testResult: 'Test result', matched: 'Matched', notMatched: 'Not matched', saved: 'Rule saved', saveFailed: 'Failed to save rule', testFailed: 'Failed to test rule', allActions: 'All actions', targetUserPlaceholder: 'Target user ID', allResults: 'All results', ban: 'Ban', unban: 'Unban', autoBan: 'Automatic ban', ruleUpdate: 'Rule update', confirmBan: 'Ban this user?', confirmUnban: 'Unban this user?', statusChangeMessage: 'This action changes account access immediately. Enter a reason to continue.', reasonPlaceholder: 'Reason (required)', reasonRequired: 'Enter an operation reason before continuing.', defaultReason: 'Manual administrator action', statusFailed: 'Failed to update account status', drawer: { label: 'Account detail', title: 'Account detail', riskScore: 'Risk score', riskLevel: 'Risk level', ipAssociations: 'IP associations', deviceAssociations: 'Device associations', timeline: 'Risk timeline', noEvents: 'No risk events', history: 'Action history', noHistory: 'No action history' },
    title: 'User Risk Control',
    description: 'Review registration risk, cases, and explainable signals. Shadow mode is active and will not reject normal registrations automatically.',
    refresh: 'Refresh data',
    loadFailed: 'The risk service is unavailable. Check service status.',
    openCases: 'Open cases', openCasesHint: 'Prioritize high-risk registrations and multi-signal events.', viewAll: 'View all', noReason: 'No additional explanation', noOpenCases: 'No open cases', noEvents: 'No risk events yet', noData: 'No data', noCases: 'No cases',
    serviceStatus: 'Service status', serviceStatusHint: 'Current policy of the independent risk service.', mode: 'Mode', failureMode: 'Failure mode', scenarioRevision: 'Scenario revision', shadowNotice: 'Shadow mode records and evaluates signals without automatically freezing or rejecting users. Any later enforcement requires an explicit rule release and human review.',
    recentEvents: 'Recent risk events', recentEventsHint: 'Each event includes the matched scenario, evidence family, and decision reason.', eventsTitle: 'Risk Events', eventsDescription: 'Review risk evidence from registrations and usage over time.', casesTitle: 'Registration Review', casesDescription: 'Resolve registration risk cases that need human confirmation.', scenariosTitle: 'Scenarios & Rules', scenariosDescription: 'Review scenario revisions and their current run mode.', subjectsTitle: 'User Profiles', subjectsDescription: 'Review event counts, highest scores, and recent actions by subject.', listsTitle: 'List Management', listsDescription: 'Review active allow, watch, and deny list entries.', auditTitle: 'Audit Log', auditDescription: 'Review administrator actions for risk cases and configuration changes.', resolve: 'Mark resolved', resolving: 'Resolving...', resolved: 'Resolved', resolutionPrompt: 'Enter a resolution note', defaultResolution: 'Manual review completed; no restriction applied', resolveSuccess: 'The case was marked as resolved.',
    table: { time: 'Time', scenario: 'Scenario', subject: 'Subject', action: 'Suggested action', reason: 'Reason', title: 'Case', priority: 'Priority', status: 'Status', updated: 'Updated', name: 'Name', code: 'Code', mode: 'Mode', revision: 'Revision', type: 'Type', events: 'Events', score: 'Max score', lastSeen: 'Last seen', actions: 'Actions', listType: 'List type', valueHash: 'Value digest', label: 'Label', actor: 'Actor', target: 'Target', account: 'Account', id: 'ID', riskType: 'Risk type', pending: 'Pending', statusChange: 'Status change', result: 'Result' },
    metrics: { openCases: 'Open cases', openCasesMeta: 'Awaiting review', events24h: 'Events in 24h', events24hMeta: 'Recent signals', highRisk: 'High-risk subjects', highRiskMeta: 'In the last 24h', reviewRate: 'Review rate', reviewRateMeta: 'Current event window' },
  },
}
