const apiBase='/api/v1/admin/extensions-self/account-monitor';
const state={page:1,page_size:20,total:0,accountId:null,tab:'models',filters:{range:'7d',platform:'',model:'',result:'',error_category:'',rollup:'physical'}};
const $=id=>document.getElementById(id);
const number=value=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2}).format(Number(value||0));
const money=value=>`$${number(value)}`;
const percent=(ok,total)=>total?`${(Number(ok)*100/Number(total)).toFixed(1)}%`:'—';
function range(){const to=new Date(),from=new Date(to);const values={"24h":1,"7d":7,"30d":30,"90d":90};from.setUTCDate(from.getUTCDate()-(values[state.filters.range]||7));return{from:from.toISOString(),to:to.toISOString()}}
function query(extra={}){const params=new URLSearchParams({...range(),page:String(state.page),page_size:String(state.page_size),...state.filters,...extra});for(const[k,v]of[...params])if(!v||k==='range')params.delete(k);return params}
async function request(path,options){const response=await fetch(`${apiBase}${path}`,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});const data=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function metric(label,value,detail=''){return `<div class="metric"><span>${label}</span><strong>${value}</strong><small>${detail}</small></div>`}
async function loadOverview(){const data=await request(`/overview?${query()}`);$('account-overview').innerHTML=[metric('账号尝试',number(data.attempts),`${number(data.failures)} 次失败`),metric('账号成功率',percent(data.successes,data.attempts),'上游尝试口径'),metric('用户请求',number(data.requests),`${percent(data.request_successes,data.requests)} 最终成功`),metric('活跃 / 异常',`${number(data.active_accounts)} / ${number(data.abnormal_accounts)}`,'物理账号'),metric('Token',number(data.tokens),money(data.user_cost)),metric('P95 延迟',data.p95_duration_ms?`${number(data.p95_duration_ms)} ms`:'—',`${number(data.users)} 位用户`)].join('');$('sync-status').textContent=data.last_sync_at?`最近同步 ${new Date(data.last_sync_at).toLocaleString()} · 延迟 ${number(data.sync_lag_seconds)} 秒`:'同步状态暂不可用'}
async function loadAccounts(){const data=await request(`/accounts?${query()}`);state.total=Number(data.total||0);$('account-count').textContent=`${number(state.total)} 个账号`;$('page-label').textContent=`第 ${state.page} 页`;$('prev-page').disabled=state.page<=1;$('next-page').disabled=state.page*state.page_size>=state.total;const rows=data.items||[];$('accounts-body').innerHTML=rows.length?rows.map(row=>`<tr data-account-id="${row.account_id}"><td><strong>${escapeHTML(row.account_name||`账号 ${row.account_id}`)}</strong><br><small>${row.parent_account_id?`母账号 ${row.parent_account_id}`:`ID ${row.account_id}`}</small></td><td>${escapeHTML(row.platform||'—')}</td><td>${number(row.attempts)}</td><td>${percent(row.successes,row.attempts)}</td><td>${number(row.failures)}</td><td>${number(row.tokens)}</td><td>${money(row.user_cost)}</td><td>${row.p95_duration_ms?`${number(row.p95_duration_ms)} ms`:'—'}</td><td><span class="health-line"><i class="health-dot ${row.health?.level||'normal'}"></i>${healthLabel(row.health?.level)}</span></td></tr>`).join(''):'<tr><td colspan="9" class="empty">当前范围没有账号调用</td></tr>';document.querySelectorAll('[data-account-id]').forEach(row=>row.addEventListener('click',()=>openDrawer(Number(row.dataset.accountId),row.querySelector('strong').textContent)))}
async function loadQuality(){const data=await request(`/data-quality?${query()}`);const rows=[['主库连接',data.source_connected?'正常':'不可用'],['错误归属率',data.error_attribution_rate==null?'暂不可用':`${(data.error_attribution_rate*100).toFixed(1)}%`],['未归属账号',number(data.unattributed_errors)],['恢复型失败',number(data.recovered_failures)],['精确 / 估算模型',`${number(data.exact_models)} / ${number(data.estimated_models)}`],['缺失请求标识',number(data.fallback_identities)],['数据来源',data.data_source||'暂不可用']];$('quality-content').innerHTML=`<div class="quality-list">${rows.map(([k,v])=>`<div class="quality-row"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>`}
async function refresh(silent=false){try{await Promise.all([loadOverview(),loadAccounts(),loadQuality()])}catch(error){if(!silent)toast(error.message,true)}}
function healthLabel(level){return({normal:'正常',attention:'关注',abnormal:'异常',critical:'严重'})[level]||'正常'}
function escapeHTML(value){const div=document.createElement('div');div.textContent=String(value??'');return div.innerHTML}
async function openDrawer(id,name){state.accountId=id;$('drawer-title').textContent=name;$('drawer-subtitle').textContent=`账号 ID ${id}`;$('account-drawer').classList.add('open');$('account-drawer').setAttribute('aria-hidden','false');$('drawer-backdrop').hidden=false;await loadDrawer()}
function closeDrawer(){$('account-drawer').classList.remove('open');$('account-drawer').setAttribute('aria-hidden','true');$('drawer-backdrop').hidden=true}
async function loadDrawer(){if(!state.accountId)return;const paths={models:`/accounts/${state.accountId}/models`,users:`/accounts/${state.accountId}/users`,errors:`/accounts/${state.accountId}/errors`,attempts:`/attempts`,media:`/accounts/${state.accountId}`};try{const data=await request(`${paths[state.tab]}?${query({account_id:String(state.accountId)})}`);$('drawer-content').innerHTML=renderDetail(state.tab,data)}catch(error){$('drawer-content').innerHTML=`<p class="error-text">${escapeHTML(error.message)}</p>`}}
function renderDetail(tab,data){const items=data.items||[];if(tab==='media')return `<div class="metric-strip">${metric('图片',number(data.image_count))}${metric('视频',number(data.video_count),`${number(data.video_duration_seconds)} 秒`)}</div>`;if(!items.length)return '<p class="empty">当前范围没有明细</p>';const columns=Object.keys(items[0]).filter(key=>!['raw_error','credentials','full_key'].includes(key));return `<div class="table-scroll"><table><thead><tr>${columns.map(key=>`<th>${escapeHTML(key==='masked_prefix'?'API Key':key)}</th>`).join('')}</tr></thead><tbody>${items.map(item=>`<tr>${columns.map(key=>`<td>${escapeHTML(item[key]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function toast(message,error=false){const node=$('toast');node.textContent=message;node.style.background=error?'#842029':'';node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2600)}
document.querySelectorAll('#account-filters input,#account-filters select').forEach(control=>control.addEventListener('change',()=>{const key=control.id.replace('-','_');state.filters[key]=control.value;state.page=1;refresh()}));
$('page-size').addEventListener('change',event=>{state.page_size=Number(event.target.value);state.page=1;loadAccounts()});$('prev-page').addEventListener('click',()=>{if(state.page>1){state.page--;loadAccounts()}});$('next-page').addEventListener('click',()=>{if(state.page*state.page_size<state.total){state.page++;loadAccounts()}});$('refresh-button').addEventListener('click',()=>refresh());$('drawer-close').addEventListener('click',closeDrawer);$('drawer-backdrop').addEventListener('click',closeDrawer);document.querySelectorAll('.tabs button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(node=>node.classList.toggle('active',node===button));state.tab=button.dataset.tab;loadDrawer()}));
$('thresholds-button').addEventListener('click',async()=>{try{const data=await request('/thresholds');$('threshold-success-rate').value=Number(data.success_rate||.9)*100;$('thresholds-dialog').showModal()}catch(error){toast(error.message,true)}});$('save-thresholds').addEventListener('click',async event=>{event.preventDefault();try{await request('/thresholds',{method:'PUT',body:JSON.stringify({scope:'global',scope_id:0,success_rate:Number($('threshold-success-rate').value)/100})});$('thresholds-dialog').close();toast('阈值已保存')}catch(error){toast(error.message,true)}});
$('rebuild-button').addEventListener('click',()=>$('rebuild-dialog').showModal());$('start-rebuild').addEventListener('click',async event=>{event.preventDefault();try{const job=await request('/rebuild-jobs',{method:'POST',body:JSON.stringify({from:new Date($('rebuild-from').value).toISOString(),to:new Date($('rebuild-to').value).toISOString()})});$('rebuild-status').textContent=`任务 ${job.id} 已提交`;}catch(error){$('rebuild-status').textContent=error.message}});
refresh();setInterval(()=>refresh(true),60000);
